# Generated by Django 5.1.2 on 2024-10-30 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='appid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission.personal'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='total',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
