# Generated by Django 5.1.2 on 2024-11-10 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0002_rename_categoty_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='empnumber',
        ),
    ]
