# Generated by Django 5.1.2 on 2024-11-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0003_remove_market_empnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='empnumber',
            field=models.IntegerField(default=0),
        ),
    ]
