# Generated by Django 4.2.16 on 2024-10-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avg',
            field=models.FloatField(default=True, editable=False),
        ),
    ]
