# Generated by Django 4.2.16 on 2024-10-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_student_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avg',
            field=models.TextField(),
        ),
    ]
