# Generated by Django 4.2.16 on 2024-10-27 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_alter_student_avg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='avg',
        ),
    ]
