# Generated by Django 4.2.6 on 2023-11-08 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student_tbl',
        ),
    ]
