# Generated by Django 4.2.6 on 2023-11-08 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0002_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
